// error.h
#ifndef CHEERS_DEFINITIONS_H
#define CHEERS_DEFINITIONS_H


#define APP_TITLE "Cheers! | Cop & Past Inc."
#define START_SCREEN_WIDTH 1536//1280
#define START_SCREEN_HEIGHT 864//720

#define SOUND_MAX_CHANNELS 8

#define GLYPHS_COUNT 128
//#define FONT_SIZE 16
#define FONT_TEXTURE_SIZE 512
#define TEXT_MAX_LENGTH 1024
#define WORD_MAX_LENGTH 32


#endif // !CHEERS_DEFINITIONS_H
