// enums.h
#ifndef CHEERS_ENUMS_H
#define CHEERS_ENUMS_H


typedef enum anchor_e {
	ANCHOR_TOP_LEFT,
	ANCHOR_TOP_CENTER,
	ANCHOR_TOP_RIGHT,
	ANCHOR_CENTER_LEFT,
	ANCHOR_CENTER_CENTER,
	ANCHOR_CENTER_RIGHT,
	ANCHOR_BOTTOM_LEFT,
	ANCHOR_BOTTOM_CENTER,
	ANCHOR_BOTTOM_RIGHT
} anchor_t;

typedef enum font_e {
	FONT_ROBOTO_REGULAR_12,
	FONT_ROBOTO_REGULAR_14,
	FONT_ROBOTO_REGULAR_16,
	FONT_ROBOTO_REGULAR_18,
	FONT_ROBOTO_REGULAR_36,
	FONT_ROBOTO_MEDIUM_14,
	FONT_ROBOTO_MEDIUM_16,
	FONT_COUNT
} font_t;

typedef enum text_align_e {
	TEXT_ALIGN_LEFT,
	TEXT_ALIGN_CENTER,
	TEXT_ALIGN_RIGHT
} text_align_t;

enum window_e {
	WINDOW_LOGIN,
	WINDOW_SIGNUP,
	WINDOW_MAIN
};

#endif // !CHEERS_ENUMS_H
