// enums.h
#ifndef CHEERS_ENUMS_H
#define CHEERS_ENUMS_H


typedef enum anchor_e {
	ANCHOR_TOP_LEFT,
	ANCHOR_TOP_CENTER,
	ANCHOR_TOP_RIGHT,
	ANCHOR_CENTER_LEFT,
	ANCHOR_CENTER_CENTER,
	ANCHOR_CENTER_RIGHT,
	ANCHOR_BOTTOM_LEFT,
	ANCHOR_BOTTOM_CENTER,
	ANCHOR_BOTTOM_RIGHT
} anchor_t;


#endif // !CHEERS_ENUMS_H
